# Generated by Django 5.1.7 on 2025-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=10)),
                ('Email', models.CharField(default='', max_length=10)),
                ('Message', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
