# Generated by Django 5.1.7 on 2025-04-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='Data',
        ),
    ]
